name: Node.js Package - Release GPR

on:
  push:
    branches:
      - master

jobs:
  publish-gpr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # Setup .npmrc file to publish to GitHub Packages
      - uses: actions/setup-node@v1
        with:
          node-version: 14.x
          registry-url: "https://npm.pkg.github.com/"
          scope: "@Watchovr"
      - run: yarn install --frozen-lockfile
      # - name: Authenticate with the GitHub Package Registry
      #   run:
      #     echo "//npm.pkg.github.com:_authToken=${{ secrets.GITHUB_TOKEN }}" >
      #     ~/.npmrc
      # Publish to GitHub Packages
      - run: yarn publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
