name: Connector - Release Package

on:
  push:
    branches:
      - master

jobs:
  publish-gpr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # Setup .npmrc file to publish to GitHub Packages
      - uses: actions/setup-node@v1
        with:
          node-version: 14.x
          registry-url: "https://npm.pkg.github.com/"
          scope: "@Watchovr"
      - run: yarn install --frozen-lockfile
      # Publish to GitHub Packages
      - run: yarn publish --access public --new-version 1.1.$(date +%s)
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
  publish-npmjs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # Setup .npmrc file to publish to GitHub Packages
      - uses: actions/setup-node@v1
        with:
          node-version: 14.x
          registry-url: "https://registry.npmjs.org/"
      - run: yarn install --frozen-lockfile
      - name: Publish to NPMJS
        run: |
          yarn config set //registry.npmjs.org/:_authToken=$NODE_AUTH_TOKEN
          yarn config set scope "@Watchovr"
          yarn config list
          yarn publish --access public --new-version 1.1.$(date +%s)
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPMJS_TOKEN}}
